"""empty message

Revision ID: 18799d597a60
Revises: 36e6c6809e4c
Create Date: 2020-06-10 19:36:23.986842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18799d597a60'
down_revision = '36e6c6809e4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pictures',
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('mimetype', sa.String(length=255), nullable=False),
    sa.Column('original', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('width', 'height', 'recipe_id')
    )
    op.drop_column('recipes', 'image_min_hash')
    op.drop_column('recipes', 'image')
    op.drop_column('recipes', 'image_hash')
    op.drop_column('recipes', 'image_min')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('image_min', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('image_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('image_min_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('pictures')
    # ### end Alembic commands ###
