"""empty message

Revision ID: 36e6c6809e4c
Revises: e6c0106e5f48
Create Date: 2020-06-05 14:48:22.906374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e6c6809e4c'
down_revision = 'e6c0106e5f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('content', sa.String(), nullable=True))
    op.drop_column('steps', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('steps', 'content')
    # ### end Alembic commands ###
