"""empty message

Revision ID: 5dc36c13f2a3
Revises: ce2b0c57966e
Create Date: 2020-05-31 19:14:44.888508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc36c13f2a3'
down_revision = 'ce2b0c57966e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name='step_recipe_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='step_pkey')
    )
    # ### end Alembic commands ###
