"""empty message

Revision ID: d6ca04afa6b7
Revises: 18799d597a60
Create Date: 2020-06-16 11:05:43.153539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ca04afa6b7'
down_revision = '18799d597a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pictures_recipe_id_fkey', 'pictures', type_='foreignkey')
    op.create_foreign_key(None, 'pictures', 'recipes', ['recipe_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pictures', type_='foreignkey')
    op.create_foreign_key('pictures_recipe_id_fkey', 'pictures', 'recipes', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
