"""empty message

Revision ID: e6c0106e5f48
Revises: cb16e30e8823
Create Date: 2020-06-05 14:44:44.513448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c0106e5f48'
down_revision = 'cb16e30e8823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_recipes_timestamp'), 'recipes', ['timestamp'], unique=False)
    op.drop_index('ix_recipe_timestamp', table_name='recipes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_recipe_timestamp', 'recipes', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_recipes_timestamp'), table_name='recipes')
    # ### end Alembic commands ###
